# Generated by Django 5.1.2 on 2024-10-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpricesdata',
            name='type',
            field=models.CharField(default='P', max_length=1),
        ),
    ]
