# Generated by Django 5.1.2 on 2024-10-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stockpricesdata_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpricesdata',
            name='type',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
