# Generated by Django 5.1.2 on 2024-10-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_stockpricesdata_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpricesdata',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockpricesdata',
            name='low_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockpricesdata',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockpricesdata',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
