# Generated by Django 5.1.2 on 2024-10-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_stockpricesdata_high_price_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockpricesdata',
            new_name='app_stockpr_symbol_226f9b_idx',
            old_name='app_stockpr_symbol_f462e3_idx',
        ),
    ]
