# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_CONFIGURATION=Dev 

# Set the working directory in the container
WORKDIR /app

# Install system dependencies for PostgreSQL
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc libpq-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy the requirements file into the container
COPY app/requirements.txt /app/

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . /app/
COPY ../manage.py /app/


RUN pwd
RUN ls

# Expose the port the app runs on
EXPOSE 8000

# Start the application using Gunicorn with dynamic configuration
CMD ["sh", "-c", "gunicorn --bind 0.0.0.0:8000 project_name.wsgi:application --configuration=${DJANGO_CONFIGURATION}"]
