# .github/workflows/ci-cd.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: blockhouse_db
          POSTGRES_USER: blockhouse_db_owner
          POSTGRES_PASSWORD: raP0wGvLNUk2
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U blockhouse_db_owner"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Adjust according to your project needs

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py migrate  # Run migrations
        python manage.py test  # Run tests

    - name: Build and push Docker image
      run: |
        docker build -t my-django-app .
        # Replace this with your Docker Hub credentials and repository
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push my-django-app

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.14.0
      with:
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
